apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Imd9QZuSp4mFNuPvwyXMSzGuaDUGiRPBWVyAO53Pd4cOdSsqiR/NJtTdGC5z04WfeUJjeARHWc0eEZJ56agveglXshhZLAkc6Wz7ouSy231dt9cdaW0zT8O4KWtLsVn2k3rBe1ZC3esVa2XcjKwb5rFfP7/xn6AXSRn8kCj2YMrOYEKcyeygSLBxMdqaX5bSDbPRUqSJEq4gIDOYn5cwexqrwSMnq8ngx/edX6oZv77mrXYXlh7tNKM1N4FiwN9ls5RMLJXKaXdu0P0xLMFM/JP+4PlKLmRpe9Y9ABU80Ryq2Q+6cDB6x/hNmnE=,iv:46dyVb4wLYD345hmQw1BclIPih/LY+lpoTOt+QUr/AE=,tag:atl3r+a2kFCRHTshRTGy2g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTjR0b1pKdHI5aHdjd0Y1
            MzFqOEY4WUtWdTBaRmYrck9CN3FFay9HbFNFCk1vQzZzeWFDMXJFUFlrK1lPYWlX
            YnQ5clpEU3R6cElmN0FIRUhFOUx0YVEKLS0tIC9ZekRTR094ckNrYi9HNnBZRW5p
            ZUV6WE9XTkdLcEZMcjlhK1ZjNVM5bjQK1s4gaywnL9OSj1flgc65+hIa5cWblVBq
            CNPLTRwsbv/07x+tONE0N9GxtPB175cS6Ejw3a/wL2yq/wFBn6uCWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dn46cz5qcvtf6ul8fz9dyyqmkcu2une03l6t6233ynjuawxfqv8s7ed5xp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T06:27:57Z"
    mac: ENC[AES256_GCM,data:9dnlVQaw0dm9Au96MnyGSeVDEvKUhiCUo29aAlJWznYcGPDZ3ngycLiBu/0E9QlGya9a9c998fF/RQ+x3hmnudIJTsLGNRLmSXgQ0D3TRE2+jnzPmxUthjEQb2VdygrpYrVeYcY9YgVXi+cvZ+z6OawEyW9uLBeoftymTy2trd8=,iv:3Q0QcoHWLHw2BQhix4Kn9D/2U+oVLUN9if27dt38Nwc=,tag:Q4ekEQAA0b0ANOr4rM2BXA==,type:str]
    version: 3.13.2
