apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:O2HaQlKFJ8e1wRxDJGai8GbH1l7LaC7VgHdv8TXr5ujC/9S3PFnmLeml5eR5EmBW6axI4TGygdAui47W9OLHmZeYKY14Y+hk/gph7RdwnlRo10Y7qK8mojEVGvD7gJjhMu62U7DyvqVc9d5QW9rBhpSgE/mo7dgX9SPRPDSlTqxgt5BBeYsRuY2e3BUwFxl7JJLqmMwMzPs/GYCYpzRGmKNeaBoZJoqpqeeGtLqJEYjlwPtoH65vk8NrR2tonT42USNTG8Hti61IduPNQBIVaTKteTJPgMtCM6sTKMgP6yFkzt0XXitmNK7eZYw=,iv:KNV27b8oyy0/LD//sxzJ7KQwrXRDAVnwAJQS31kC6Yk=,tag:k2KKaNuWO9XEr3mF3WIU7w==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcE5BNnErMENDSGNnSGtq
            cTFLejZsVStyMk91a3VnR05kcVR2akNWaFU4Ckc4RzdKaHgveHBGOXRndndEcUxC
            NURaQU5GV01NaDMzeXowc014YzgyRVUKLS0tIGJQQmE1RTRkYUxBUFRxakJ5ZEpt
            K3RvYmVmL1RHVVgweTZYS3R4RTkrbkEKtkQh6war/w9TpBkTj2d4PY6IgvIjzOUV
            FCVQnbq2haGhXZD0IKbih0XRoxJa6k13LLGYBy3jzr7dQg/Bgli93g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dn46cz5qcvtf6ul8fz9dyyqmkcu2une03l6t6233ynjuawxfqv8s7ed5xp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T00:38:58Z"
    mac: ENC[AES256_GCM,data:uSKMdCDWB3aKOJCOKKtqmz9UZKhr4WGfFIxg5sgNXEeNt+EvVQ8w7BvD4KxaBBXgRpeMCr7H9zMLO24egGd47ilbSdOxKyT+2Ghf3g+hNxXX0JixUZ6KJ8Cq9EKYXv88TPjAlHzRjDJVH3KK8F+3KFQ/YxBQde/odPCEBN4TzxE=,iv:qhbwIs9v2VuUZZJjR1zD3AZa58xvqidSd6uVE/AIKBs=,tag:LEX9iOeflkZQjFiBqygxCQ==,type:str]
    version: 3.13.2
