apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:TJatm5/LGlRHEKphNICtQejoP8Zrl9mEyX3VyD9rXi55IcH3uC1jPgIKfQGrlxvfKl17KVfw9cu4ZtiNdACw9I9v89muPu6UU1Ju4VQjnpMtTF6L63/wrky8KWZMdVYP1atEerwOq5i+Inl15PUGODgA6LtbvURCXo9VGn8UTtRFvoVP42sR9pscA+ZWvXtz9ieLVX9SYE+TZe+OqPb4Jg3JqyXyJjbZvDmsR86j8atD1eaAx4zCGH7Sk7RTUSYwjV4gLGwx4H/qGehJUlXMoevqQGsCJ9rd+VIOVYYuYJlm/F6EnlPCHPF7ETmZ5MP2,iv:TkEgWBW1l29l1Iets1Kq+jbU+SHD3WVjN+mFff+Qxjc=,tag:UQxLRrdL7VjxiFOTCaZztQ==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZTBpM0NvNWR1YnVTeHpI
            ejI2TXRIOUNUaVEweWxMRG1TRmpnb1ExQkEwCkxnZlJmOVNGVHFnQW1vbm1yN3Rv
            cUpQQ21VTGsvTzA2MWxUQ3RvZ1Q1eEUKLS0tIFRCcWRUQ2V5ODVHNHRDR1RRUEha
            KzV0R1d6dHFsV01MUGdiYkhyN2dnS2sKW3dmEuN6AKY+BlAWpW9/tbq3/TldgwSD
            kImC/b3raZCDd9MOeBiWD2ZgPfeY1+LW+ZjuUUkPrQeuv4JsM/xUnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dn46cz5qcvtf6ul8fz9dyyqmkcu2une03l6t6233ynjuawxfqv8s7ed5xp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T08:45:56Z"
    mac: ENC[AES256_GCM,data:7n4cSzUjHqYHQ79Ni+KUltV+gPOTL0ztMrZmtyFjmFf5YgTZ3R0zXILkta49qex8U1qz0XtXDwvpwkQiUmKBOm9tHQlawUaVxocOqOosh7VhZvQfhwGdtmMn7C1n4W43x2X1MaiOjEj7CHgY/E2PCof/arJ9Y+ia3nXCOV02L8s=,iv:+gV7ESvt8qtbdxqVGYt9eLz7Rrx0Mq+P31KvtT3f8J4=,tag:zoN4r8MzxKwbRBXayyu8MA==,type:str]
    version: 3.13.3
