apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timefold
resources:
  - ../../base/timefold/
  - cloudflare.yaml
  - tunnel-credentials.yaml
  - ghcr-pull-secret.yaml
  - timefold-session-secret.yaml
