apiVersion: v1
data:
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:5SO2ea2DEheY375YuWiKW01azV4Z+7ElQHRXII6LlNOfTgvHxGREsvdFDJh1epBWK7C/PAKvp3djBuVs,iv:7AwurVH+9GGYuo5R5rxC6FsEO+0tpYzCAbNhFvETQ2c=,tag:PBachkF2eXblk02NDZCE7g==,type:str]
kind: Secret
metadata:
    name: timefold-session-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVowdXF5UzB3aVdSVFFl
            Umwxa2J3dUZLZzVsR2ZTS2tLaXcvZHNUV2tRCmJJSGd0QnRVNjlONjdlQXhqWHMr
            dGQyd01sREVZditGbUhQNmUyMnNOOHMKLS0tIFg4S3NoTzdpWllmeFh6ajAwMXky
            bGJkSW91SDRDbmJadXJNZWVkeEhEOTgKYLne2ssqPdlGppTn/hV+EYM9N4194lvK
            d8TcQUUlsTWM8kGY18RF7bpBMNortjxsJeRJP3uk0J4tsgOI01EGJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dn46cz5qcvtf6ul8fz9dyyqmkcu2une03l6t6233ynjuawxfqv8s7ed5xp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:36:33Z"
    mac: ENC[AES256_GCM,data:Rsm/NhJfRSe8PptBcDBYqHFw5kAetBJBZIUTq78Tg1Z2hVPcdwd+T2SDWkju2YH0YQ5ge5dLj5nqA3wsowHuSsC9OJjaCFQ+ry6b3Wh5M8IWkb4RiT1vhTEJxicksInUC8O04QZhUublhsivKzMiz+JvH6N01heE4DoiW2WjG1M=,iv:c07FLAjyKxlXAU08oEDaNiQtNd3dC/gLdAKSUx7LBc4=,tag:TgTCf2Fe0iimtWWFi3t+kA==,type:str]
    version: 3.13.3
