apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:l70Q7zSyjiaKCmDQPgGl6PpAx9lzv2XBbMShq/lzCs7uwnZr401MJU01ZqWC6/iml8+dBAqqwgy6Q97r7XDvTadXXspEroJL+tgwtLYoq71q9diBbIB2YG3xeqmzLWx/Z2ZIBRcwsSYDjlU7ptY9sWA1cmM5JM55Yk4XHXmqQfwZu+GuGBTnhE6pQeTMBDvF6W9YISciOZq2wUd+skAgAkXcQLWJ/zXKQqniUW10ZRyWWXyn3h2QjQK8pvbvvHzoPg5UtAL61ghFha/CYWyJwIB50gjp2T2YwVA3hV84DM3vnwqjV1KaLai9G/Y=,iv:BzV+Igvz9vZcbeMNDHTArO8LsAIVi/iOq1TEeb4P+H8=,tag:cp5FlAu8vb2jnTRKaIs2Hw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUFFES2I1cWtrRkdnMXZR
            TSttN2pnMkxra0hFUGxPalJsRU1BTllySWpnClJTYStyRTBPaGFoQys5YjRSeERM
            UldBdk16YlpiNWdFSStMU3FWdlNNUmMKLS0tIDRsSHNBQlErY052clYwOUNiWTZR
            b3ExVjBrMVRhTHh6Nm9GbmhBaUY0UW8KJHoWvIh1ljY0Zj7fJva210Rrs7B4mqj+
            m7S1cZlG5I6Tl2IBmdYj/yGpMI83dcYvU1Rybx57GJ1bRaEfpa+q6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dn46cz5qcvtf6ul8fz9dyyqmkcu2une03l6t6233ynjuawxfqv8s7ed5xp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T08:45:42Z"
    mac: ENC[AES256_GCM,data:aN5TJnpGd/v8Vw3bk5gS0V/1wAstjGxF+7+aa1LomNdFt4IaPXRApSKpawapjxsnyDiaVHEhKGv2KBqbsAikBNRHF+c0+wyFPthCo2SuGOrScWEkLrSpZ0oxPiHPe/hCwqmUKj68q8eSzgpewyD7nNYnm11miyJ92GzDBgz6eBI=,iv:8boxKHZtOMQb/XfTJSSe+QLr33KW+DveLIgOK/BHvbg=,tag:lC7G5njG0RyiN6QETepVTA==,type:str]
    version: 3.13.3
