kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-metadata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 750Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-audiobooks
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
Lind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-podcasts
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

