apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:4UterFNi3fNM5hw6,iv:x5pF0T3kTaz2JQRBm78B5KMn3CaDa2cmuLQwxvKJtq8=,tag:9lbqs1xt8hDorftUUlOpwQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:2pTOuSLkdsmBsw4D0SlsTEMCKMbOHPMS,iv:HEf5P7E3lSb3s+HsSzepGgCkprZsdTHKw7AOOgvTJBw=,tag:ylymikA1+zql9i91V2xFTw==,type:str]
kind: Secret
metadata:
    name: linkding-admin
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT21ETzhJcHIxNUI1cnRi
            QkMwVTUwRFZtZlI0dHJvMUc4b3FqM2JqY3dnCm9qMjdpM2ZmL0w1K3NoT09CQ0VH
            ZjZYdXdpeFI4SmpTcHNCa21BeFFtOGcKLS0tIGVkZ2N2SmpkYlRjR0YwdjQrdU5E
            VWs3cStlc2Y1MHpVWnVSbE5kNW9Ra0EKeh1zn10Z6OssrUisK6TD+pgLf68CYcUr
            jpQ1wfT7ytKd5aNCNgpAn4chpkcunYQsLl3Rf96vgzauWE5QTliYaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dn46cz5qcvtf6ul8fz9dyyqmkcu2une03l6t6233ynjuawxfqv8s7ed5xp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T04:04:47Z"
    mac: ENC[AES256_GCM,data:PB6cX/Ebw7SAvdYtQ14bob+XkSubTNHrl0gUDY486OFE07DhCc32Ize11DwiP/qgqlQEyf5NLM3T4dyW1q3ug715OU6fKqBz+rkAxM16IMZgn++IV8Vi4XLGYBCuv8vMlP/VT26zSJwxZJVhppeIq4FNKUK6bZ3PP43HpcBcu+w=,iv:libFJBTn7HUj4FQjxs58c8wlWF3jacwoijbO3VhD3ZQ=,tag:fC6IFjqFdmX+99gliUiU4w==,type:str]
    version: 3.13.2
