apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Ypdx+orrWMOeP+JpFDIYVwYlr71uf6ZZNYBa4YHH/BVPoyStvT9R0CEwYCDzOYujpIbaR/Xv4FXW+z7OhLkV1aobzVHSCybXXCT5gQ0dElC+D/D0+zV5JbGaGTSZSbnpPiKd7HCLWIsHuUZArqHr+1hdFamciOTI3cHsI4sjUFD8s2tQ2Kw/FnuVb63FdSzdLU7+to2d6YRbH2zGbCH+vJk7OgVXd+Fu9wr28oxQIHivGDX64rlRaxogoX8x9Cx2b+eV6XMxLSxgykyqI5vpfNhRbnuCXoKDwx8U+mWxgoKHk7IjU3mIOva3mNo=,iv:qikgrdnUU9F01wH+2tezUlx0aLmDrDm+1+VMqImSQoE=,tag:MdfhOZiSlx5g3H/rrtJZgg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UlhBYVkwYmVqdVRnNWdE
            TnNLZnk1Mmlyd3ZmalN0bFYxdDBHZVNxbGpVCmtYMXlXckN4VUJXT1d3SG4zaUpu
            S2wvSzRINzJuYUo2MVJDeG9pTzVoTjAKLS0tIFJuSVJHVnlwdDFNZE1uY1M4ZGF5
            MjVkbThqdG5OYXc3Y29qbTZJQ1BmYzAKxQhOyqxv2dRC8tnZRF0F85kGGstPFliE
            E3kBmDMkyCLLWczB6pXAeZTrHi00JVLVNH+QHFqxTrpwlZRHhw5HXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dn46cz5qcvtf6ul8fz9dyyqmkcu2une03l6t6233ynjuawxfqv8s7ed5xp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T02:20:55Z"
    mac: ENC[AES256_GCM,data:8ElPtpP/FPXvJJ9kKriEnoLaPAaVuzC8RXa8sayiXRLOXBGp1XCFxMKaE1UFfMwNGd5b++FpcI/+7B1axZ7wNe8C256mbFdO7KQlZzb2DB0g4JQqJdn+X3dMyB0+G5mwmI4nXO+HLFufG4LD/Elm1ijeiOsTrfApkGlwpWYbN9Q=,iv:6ucUdCI14W+YS+UsnC6+ZwC/0+vQowIFzg/HHuMog+g=,tag:HrswRw3SVTmZjewF9trkzg==,type:str]
    version: 3.13.2
