apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:mkBsy1Altc1vV9t1khhH7vPkb19/SMKJJ4qZP++0YGH5lMKI5K4A2uL6xGfml+5Cl/8Jnw2vFQuQsimh1nEazqNCso3uTCOsaFCYE5l0PLVKLH1tQ0vyWXXwZd5/bIZCezrbQAp0QPKLo5IKFLmayv+cZknRWu56sKHkPKA7GNr0LziUVY9Ex9HhqqQFZbxVz5U35CtU4R1hwML7NTANIu+BrrUobE1ax7+yo/qnseYeF1idg73zzlLytejr/UIfY/8waObDhg+vil61ZQw+FKtMpR/9SWico5qPombGo14ep2hXh96+fdhZg9o=,iv:evV4iL9ssBC9iyFUMqs3sqF0GITw5Ex6OkSvCkKSPqE=,tag:mergANogcP6hQ2p4Gbi3OQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRFordjlobStVYWdabzVQ
            MTVwUjlrczVSQ3RtUUIvN083cnhSRkYvQ3cwCkg0YnV6TmsyM2NkUkJ4NWY1VmZq
            dGFnL1RORWxhMXdzNEpsdTV5RzIzZjQKLS0tIDhJUGZzZHpZd2R3WmNsRE9BU21M
            UDB5MzBJL2NTWkcweUlmek9scEJnWncKkb2xFStugFA5Hp63+a5c5P86P1FUg0K3
            bIVVGUlrVssua/HvrWvBGSiCDjIt08ieVkUAJxBD7UBusAZMKg0nmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dn46cz5qcvtf6ul8fz9dyyqmkcu2une03l6t6233ynjuawxfqv8s7ed5xp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T03:19:40Z"
    mac: ENC[AES256_GCM,data:Se3y3N7PjsQPd318pQZ95p420T6RCuZioZcbaqkuf12zfAsus3f/yDYahxxJf8vi93ae7gD+4E0CWb2KG8QU1s0cfLnLNZoK1l9atU6SswtqZd1EiF/KisxIp+qO13A0JdDT+vEu8wGMfHqM1pd+1VCP9CGS8tbD5FCQQjINXlQ=,iv:eebtN1fRmmtj06tzeuEq6GdTDXpPKhFoeA2jkiII+jI=,tag:oIerzf7EKmwqErX0o7lqyQ==,type:str]
    version: 3.13.2
